name: Build and deploy blog / Heartbeat (final letter)

on:
  push:
    branches: [main]
    paths:
      - 'source_txt/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run heartbeat updater
        run: python scripts/heartbeat.py

      - name: Build site
        run: python scripts/build.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs source_txt/final_letter.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: rebuild dev blog (with heartbeat)" && git push
          fi
