name: Sync Images

on:
  push:
    paths:
      - 'source_img/**'

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # フル履歴を取得して diff に備える

    - name: Prepare image list
      run: |
        mkdir -p dev_blog/image/
        if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
          echo "初回コミットまたは履歴が無いため、source_img 全部をコピー対象にします"
          find source_img -type f > changed.txt
        else
          echo "差分検出中: ${{ github.event.before }} → ${{ github.sha }}"
          git fetch origin
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- source_img/ > changed.txt
        fi

    - name: Copy changed images to dev_blog
      run: |
        while read file; do
          target="dev_blog/image/${file#source_img/}"
          mkdir -p "$(dirname "$target")"
          cp "$file" "$target"
          echo "[copy] $file → $target"
        done < changed.txt

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add dev_blog/image/
        git commit -m "Auto sync new/updated images" || echo "No changes"
        git push
